
#ifndef _Z01_A19_GATEWAY_APP_DEF_
#define _Z01_A19_GATEWAY_APP_DEF_


#define SENGLED_UART_APP


#define COLOR_TEMPRATURE_MAX 370
#define COLOR_TEMPRATURE_MIN 153
#define COLOR_TEMPRATURE_D_VALUE  (COLOR_TEMPRATURE_MAX-COLOR_TEMPRATURE_MIN)


#endif
