
#ifndef _Z01_A19_HV1_APP_DEF_
#define _Z01_A19_HV1_APP_DEF_

/*  ×¢ÊÍÐÅÏ¢ */
// sengled 2015.6.24 wms


//#define THE_GATEWAY_TYPE_SENGLED_WMS

//#define SENGLED_Z01_A19_UART

#define COLOR_TEMPRATURE_MAX 370
#define COLOR_TEMPRATURE_MIN 153
#define COLOR_TEMPRATURE_D_VALUE  (COLOR_TEMPRATURE_MAX-COLOR_TEMPRATURE_MIN)




#endif

