// This file is generated by Ember Desktop.  Please do not edit manually.
//
//



#include "app/framework/include/af.h"
#include "app/framework/cli/custom-cli.h"


void changeKeyCommand(void);
void echoCommand(void);
void emAfCliBsendCommand(void);
void emAfCliInfoCommand(void);
void emAfCliRawCommand(void);
void emAfCliReadCommand(void);
void emAfCliSendCommand(void);
void emAfCliTimesyncCommand(void);
void emAfCliVersionCommand(void);
void emAfCliWriteCommand(void);
void emAfPluginIdentifyCliPrint(void);
void emberAfPluginAddressTableAddCommand(void);
void emberAfPluginAddressTableLookupCommand(void);
void emberAfPluginAddressTableRemoveCommand(void);
void emberAfPluginConcentratorAggregationCommand(void);
void emberAfPluginConcentratorPrintSourceRouteTable(void);
void emberAfPluginConcentratorStartDiscovery(void);
void emberAfPluginConcentratorStatus(void);
void emberAfPluginConcentratorStopDiscovery(void);
void emberAfPluginCountersClear(void);
void emberAfPluginCountersPrintCommand(void);
void emberAfPluginCountersPrintThresholdsCommand(void);
void emberAfPluginCountersResetThresholds(void);
void emberAfPluginCountersSendRequestCommand(void);
void emberAfPluginCountersSetThresholdCommand(void);
void emberAfPluginCountersSimplePrintCommand(void);
void emberAfPluginIdleSleepAwakeWhenNotJoinedCommand(void);
void emberAfPluginIdleSleepStatusCommand(void);
void emberAfPluginIdleSleepStayAwakeCommand(void);
void emberAfPrintAllOff(void);
void emberAfPrintAllOn(void);
void emberAfPrintAttributeTable(void);
void emberAfPrintStatus(void);
void enableDisableEndpoint(void);
void endpointPrint(void);
void findJoinableNetworkCommand(void);
void findUnusedPanIdCommand(void);
void getSetMfgToken(void);
void helpCommand(void);
void interpanCommand(void);
void interpanLongCommand(void);
void keysClearCommand(void);
void keysDeleteCommand(void);
void keysPrintCommand(void);
void networkChangeChannelCommand(void);
void networkExtendedPanIdCommand(void);
void networkFormCommand(void);
void networkIdCommand(void);
void networkInitCommand(void);
void networkJoinCommand(void);
void networkLeaveCommand(void);
void networkPermitJoinCommand(void);
void networkRejoinCommand(void);
void networkSetCommand(void);
void optionAddressTablePrintCommand(void);
void optionAddressTableSetCommand(void);
void optionApsRetryCommand(void);
void optionApsSecurityCommand(void);
void optionBindingTableClearCommand(void);
void optionBindingTablePrintCommand(void);
void optionBindingTableSetCommand(void);
void optionDiscoverCommand(void);
void optionEndDeviceBindCommand(void);
void optionInstallCodeCommand(void);
void optionLinkCommand(void);
void optionPrintRxCommand(void);
void optionRegisterCommand(void);
void printAllLibraryStatus(void);
void printOffCommand(void);
void printOnCommand(void);
void printTimeCommand(void);
void resetCommand(void);
static void rgbCalibrationCommand(void) {
  zclSimpleClientCommand( ZCL_RGB_CALIRATION_CLUSTER_ID,
                          ZCL_RGB_CALIBRATION_COMMAND_ID);
}

static void zclBasicRtfdCommand(void) {
  zclSimpleClientCommand( ZCL_BASIC_CLUSTER_ID,
                          ZCL_RESET_TO_FACTORY_DEFAULTS_COMMAND_ID);
}

static void zclColorcontrolEmovehueCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_ENHANCED_MOVE_HUE_COMMAND_ID);
}

static void zclColorcontrolEmovetohueCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_ENHANCED_MOVE_TO_HUE_COMMAND_ID);
}

static void zclColorcontrolEmovetohueandsatCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_ENHANCED_MOVE_TO_HUE_AND_SATURATION_COMMAND_ID);
}

static void zclColorcontrolEstephueCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_ENHANCED_STEP_HUE_COMMAND_ID);
}

static void zclColorcontrolLoopCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_COLOR_LOOP_SET_COMMAND_ID);
}

static void zclColorcontrolMovecolorCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_COLOR_COMMAND_ID);
}

static void zclColorcontrolMovecolortempCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_COLOR_TEMPERATURE_COMMAND_ID);
}

static void zclColorcontrolMovehueCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_HUE_COMMAND_ID);
}

static void zclColorcontrolMovesatCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_SATURATION_COMMAND_ID);
}

static void zclColorcontrolMovetocolorCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_TO_COLOR_COMMAND_ID);
}

static void zclColorcontrolMovetocolortempCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_TO_COLOR_TEMPERATURE_COMMAND_ID);
}

static void zclColorcontrolMovetohueCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_TO_HUE_COMMAND_ID);
}

static void zclColorcontrolMovetohueandsatCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_TO_HUE_AND_SATURATION_COMMAND_ID);
}

static void zclColorcontrolMovetosatCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_TO_SATURATION_COMMAND_ID);
}

static void zclColorcontrolStepcolorCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_STEP_COLOR_COMMAND_ID);
}

static void zclColorcontrolStepcolortempCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_STEP_COLOR_TEMPERATUE_COMMAND_ID);
}

static void zclColorcontrolStephueCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_STEP_HUE_COMMAND_ID);
}

static void zclColorcontrolStepsatCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_STEP_SATURATION_COMMAND_ID);
}

static void zclColorcontrolStopmovestepCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_STOP_MOVE_STEP_COMMAND_ID);
}

void zclGlobalCommandDiscoveryCommand(void);
void zclGlobalDirectionCommand(void);
void zclGlobalDiscoverCommand(void);
void zclGlobalExpectReportFromMeCommand(void);
void zclGlobalReadCommand(void);
void zclGlobalReportCommand(void);
void zclGlobalReportReadCommand(void);
void zclGlobalSendMeAReportCommand(void);
void zclGlobalWriteCommand(void);
static void zclIdentifyIdCommand(void) {
  zclSimpleClientCommand( ZCL_IDENTIFY_CLUSTER_ID,
                          ZCL_IDENTIFY_COMMAND_ID);
}

void zclIdentifyOffCommand(void);
void zclIdentifyOnCommand(void);
static void zclIdentifyQueryCommand(void) {
  zclSimpleClientCommand( ZCL_IDENTIFY_CLUSTER_ID,
                          ZCL_IDENTIFY_QUERY_COMMAND_ID);
}

static void zclIdentifyTriggerCommand(void) {
  zclSimpleClientCommand( ZCL_IDENTIFY_CLUSTER_ID,
                          ZCL_TRIGGER_EFFECT_COMMAND_ID);
}

static void zclLevelControlMoveCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_COMMAND_ID);
}

static void zclLevelControlMvToLevelCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_TO_LEVEL_COMMAND_ID);
}

static void zclLevelControlOMoveCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_WITH_ON_OFF_COMMAND_ID);
}

static void zclLevelControlOMvToLevelCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_TO_LEVEL_WITH_ON_OFF_COMMAND_ID);
}

static void zclLevelControlOStepCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_STEP_WITH_ON_OFF_COMMAND_ID);
}

static void zclLevelControlOStopCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_STOP_WITH_ON_OFF_COMMAND_ID);
}

static void zclLevelControlStepCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_STEP_COMMAND_ID);
}

static void zclLevelControlStopCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_STOP_COMMAND_ID);
}

void zclMfgCodeCommand(void);
static void zclOnOffOffCommand(void) {
  zclSimpleClientCommand( ZCL_ON_OFF_CLUSTER_ID,
                          ZCL_OFF_COMMAND_ID);
}

static void zclOnOffOffeffectCommand(void) {
  zclSimpleClientCommand( ZCL_ON_OFF_CLUSTER_ID,
                          ZCL_OFF_WITH_EFFECT_COMMAND_ID);
}

static void zclOnOffOnCommand(void) {
  zclSimpleClientCommand( ZCL_ON_OFF_CLUSTER_ID,
                          ZCL_ON_COMMAND_ID);
}

static void zclOnOffOnrecallCommand(void) {
  zclSimpleClientCommand( ZCL_ON_OFF_CLUSTER_ID,
                          ZCL_ON_WITH_RECALL_GLOBAL_SCENE_COMMAND_ID);
}

static void zclOnOffOntimedoffCommand(void) {
  zclSimpleClientCommand( ZCL_ON_OFF_CLUSTER_ID,
                          ZCL_ON_WITH_TIMED_OFF_COMMAND_ID);
}

static void zclOnOffToggleCommand(void) {
  zclSimpleClientCommand( ZCL_ON_OFF_CLUSTER_ID,
                          ZCL_TOGGLE_COMMAND_ID);
}

static void zclSmFpCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_REQUEST_FAST_POLL_MODE_COMMAND_ID);
}

static void zclSmGpCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_GET_PROFILE_COMMAND_ID);
}

void zclTestResponseOffCommand(void);
void zclTestResponseOnCommand(void);
void zclTimeCommand(void);
void zdoActiveEpCommand(void);
void zdoAddClusterCommand(void);
void zdoBindCommand(void);
void zdoClearClusterCommand(void);
void zdoIeeeAddressRequestCommand(void);
void zdoLeaveRequestCommand(void);
void zdoMatchCommand(void);
void zdoNetworkUpdateChannelCommand(void);
void zdoNetworkUpdateScanCommand(void);
void zdoNetworkUpdateSetCommand(void);
void zdoNodeCommand(void);
void zdoNwkAddressRequestCommand(void);
void zdoPowerDescriptorRequestCommand(void);
void zdoRouteRequestCommand(void);
void zdoSimpleCommand(void);
void zdoUnbindGroupCommand(void);
void zdoUnbindUnicastCommand(void);
PGM_P zdoUnbindGroupCommandArguments[] = {
  "Target node ID",
  "The source EUI64 of the binding (the remote device's EUI64)",
  "The source endpoint of the binding.",
  "The cluster ID to unbind.",
  "The group address in the binding",
  NULL
};

PGM_P zdoUnbindUnicastCommandArguments[] = {
  "Target node ID",
  "The source EUI64 of the binding (the remote device's EUI64)",
  "The source endpoint of the binding.",
  "The cluster ID to unbind.",
  "The destination EUI64 in the binding (usually the local node's EUI64",
  "The destination endpoint of the binding",
  NULL
};

EmberCommandEntry zdoUnbindCommands[] = {
  emberCommandEntryActionWithDetails("group", zdoUnbindGroupCommand, "vbuvv", "Sends an unbind request for a multicast binding to the target device.", zdoUnbindGroupCommandArguments),
  emberCommandEntryActionWithDetails("unicast", zdoUnbindUnicastCommand, "vbuvbu", "Sends an unbind request for a unicast binding to the target device.", zdoUnbindUnicastCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zdoOutClListAddCommandArguments[] = {
  "Client cluster ids",
  NULL
};

EmberCommandEntry zdoOutClListCommands[] = {
  emberCommandEntryActionWithDetails("add", zdoAddClusterCommand, "v", "Add clusters to the known client (out) clusters on this device.", zdoOutClListAddCommandArguments),
  emberCommandEntryActionWithDetails("clear", zdoClearClusterCommand, "", "Clear the ZDO list of client (out) clusters.", NULL),
  emberCommandEntryTerminator()
};

PGM_P zdoNwkUpdChanCommandArguments[] = {
  "One byte channel to change to.",
  NULL
};

PGM_P zdoNwkUpdScanCommandArguments[] = {
  "Two byte short id of the target device",
  "One byte scan duration. Must be in range 0 - 5",
  "Number of scans to perform. Must be in range 1 - 8",
  NULL
};

PGM_P zdoNwkUpdSetCommandArguments[] = {
  "Two byte network manager id",
  "Four byte channel mask",
  NULL
};

EmberCommandEntry zdoNwkUpdCommands[] = {
  emberCommandEntryActionWithDetails("chan", zdoNetworkUpdateChannelCommand, "u", "Sends an update channel request.", zdoNwkUpdChanCommandArguments),
  emberCommandEntryActionWithDetails("scan", zdoNetworkUpdateScanCommand, "vuv", "Performs an energy scan.", zdoNwkUpdScanCommandArguments),
  emberCommandEntryActionWithDetails("set", zdoNetworkUpdateSetCommand, "vw", "Broadcasts the ID of the new network manager and active channels.", zdoNwkUpdSetCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zdoInClListAddCommandArguments[] = {
  "Server cluster id",
  NULL
};

EmberCommandEntry zdoInClListCommands[] = {
  emberCommandEntryActionWithDetails("add", zdoAddClusterCommand, "v", "Add clusters to the known server (in) clusters on this device.", zdoInClListAddCommandArguments),
  emberCommandEntryActionWithDetails("clear", zdoClearClusterCommand, "", "Clear the ZDO list of server (in) clusters.", NULL),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableZdoActiveCommandArguments[] = {
  "Two byte short id, destination for the active endpoint request",
  NULL
};

PGM_P emberCommandTableZdoBindCommandArguments[] = {
  "Two byte destination node id",
  "Remote device's source endpoint to bind",
  "Remote endpoint to bind",
  "Cluster on which to bind",
  "Remote node EUI64",
  "Binding's dest EUI64.  Usually the local node's EUI64",
  NULL
};

PGM_P emberCommandTableZdoIeeeCommandArguments[] = {
  "Short address of the device for which a long address is requested",
  NULL
};

PGM_P emberCommandTableZdoLeaveCommandArguments[] = {
  "Target node ID",
  "Remove children",
  "Rejoin after leave",
  NULL
};

PGM_P emberCommandTableZdoMatchCommandArguments[] = {
  "Two byte node id indicating wher",
  "Two byte profile id for the match descriptor request",
  NULL
};

PGM_P emberCommandTableZdoNodeCommandArguments[] = {
  "Two byte address for the target device.",
  NULL
};

PGM_P emberCommandTableZdoNwkCommandArguments[] = {
  "IEEE address for which a short address is being requested",
  NULL
};

PGM_P emberCommandTableZdoPowerCommandArguments[] = {
  "Target node ID",
  NULL
};

PGM_P emberCommandTableZdoRouteCommandArguments[] = {
  "Target node ID",
  "The index of the remote node's routing table to request.",
  NULL
};

PGM_P emberCommandTableZdoSimpleCommandArguments[] = {
  "Short address of the device where the simple descriptor request should ...",
  "The endpoint on the target device where the simple descriptor request  ...",
  NULL
};

EmberCommandEntry emberCommandTableZdoCommands[] = {
  emberCommandEntryActionWithDetails("active", zdoActiveEpCommand, "v", "Send an active endpoint request to the device with the given short id.", emberCommandTableZdoActiveCommandArguments),
  emberCommandEntryActionWithDetails("bind", zdoBindCommand, "vuuvbb", "Send a ZDO Bind command to a device specified in the command arguments ...", emberCommandTableZdoBindCommandArguments),
  emberCommandEntryActionWithDetails("ieee", zdoIeeeAddressRequestCommand, "v", "Request an ieee address based on a given node id.", emberCommandTableZdoIeeeCommandArguments),
  emberCommandEntrySubMenu("in-cl-list", zdoInClListCommands, ""),
  emberCommandEntryActionWithDetails("leave", zdoLeaveRequestCommand, "vuu", "Send a ZDO Management Leave command to the target device.", emberCommandTableZdoLeaveCommandArguments),
  emberCommandEntryActionWithDetails("match", zdoMatchCommand, "vv", "Sends a matchDescriptorsRequest to the given destination with the give ...", emberCommandTableZdoMatchCommandArguments),
  emberCommandEntryActionWithDetails("node", zdoNodeCommand, "v", "Sends a node descriptor request to a given target device", emberCommandTableZdoNodeCommandArguments),
  emberCommandEntryActionWithDetails("nwk", zdoNwkAddressRequestCommand, "b", "Sends a network address request for the given IEEE address.", emberCommandTableZdoNwkCommandArguments),
  emberCommandEntrySubMenu("nwk-upd", zdoNwkUpdCommands, ""),
  emberCommandEntrySubMenu("out-cl-list", zdoOutClListCommands, ""),
  emberCommandEntryActionWithDetails("power", zdoPowerDescriptorRequestCommand, "v", "Send a ZDO Power Descriptor Request to the target device.", emberCommandTableZdoPowerCommandArguments),
  emberCommandEntryActionWithDetails("route", zdoRouteRequestCommand, "vu", "Send a ZDO route request command to the target.", emberCommandTableZdoRouteCommandArguments),
  emberCommandEntryActionWithDetails("simple", zdoSimpleCommand, "vu", "Sends out a simple descriptor request for the short address and endpoi ...", emberCommandTableZdoSimpleCommandArguments),
  emberCommandEntrySubMenu("unbind", zdoUnbindCommands, ""),
  emberCommandEntryTerminator()
};

EmberCommandEntry testResponseCommands[] = {
  emberCommandEntryActionWithDetails("off", zclTestResponseOffCommand, "", "Sets a flag so that the application framework WILL NOT respond to the  ...", NULL),
  emberCommandEntryActionWithDetails("on", zclTestResponseOnCommand, "", "Sets a flag so that the application framework WILL respond to the next ...", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry zclTestCommands[] = {
  emberCommandEntrySubMenu("response", testResponseCommands, ""),
  emberCommandEntryTerminator()
};

PGM_P zclSmFpCommandArguments[] = {
  "fast poll update period",
  "duration",
  NULL
};

PGM_P zclSmGpCommandArguments[] = {
  "interval channel",
  "end time",
  "number of periods",
  NULL
};

EmberCommandEntry zclSmCommands[] = {
  emberCommandEntryActionWithDetails("fp", zclSmFpCommand, "uu", "Command to request fast poll mode.", zclSmFpCommandArguments),
  emberCommandEntryActionWithDetails("gp", zclSmGpCommand, "uwu", "Command description for GetProfile", zclSmGpCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zclOnOffOffeffectCommandArguments[] = {
  "effect id",
  "effect variant",
  NULL
};

PGM_P zclOnOffOntimedoffCommandArguments[] = {
  "on off control",
  "on time",
  "off wait time",
  NULL
};

EmberCommandEntry zclOnOffCommands[] = {
  emberCommandEntryActionWithDetails("off", zclOnOffOffCommand, "", "Command description for Off", NULL),
  emberCommandEntryActionWithDetails("offeffect", zclOnOffOffeffectCommand, "uu", "Command description for OffWithEffect", zclOnOffOffeffectCommandArguments),
  emberCommandEntryActionWithDetails("on", zclOnOffOnCommand, "", "Command description for On", NULL),
  emberCommandEntryActionWithDetails("onrecall", zclOnOffOnrecallCommand, "", "Command description for OnWithRecallGlobalScene", NULL),
  emberCommandEntryActionWithDetails("ontimedoff", zclOnOffOntimedoffCommand, "uvv", "Command description for OnWithTimedOff", zclOnOffOntimedoffCommandArguments),
  emberCommandEntryActionWithDetails("toggle", zclOnOffToggleCommand, "", "Command description for Toggle", NULL),
  emberCommandEntryTerminator()
};

PGM_P zclLevelControlMoveCommandArguments[] = {
  "move mode",
  "rate",
  NULL
};

PGM_P zclLevelControlMvToLevelCommandArguments[] = {
  "level",
  "transition time",
  NULL
};

PGM_P zclLevelControlOMoveCommandArguments[] = {
  "move mode",
  "rate",
  NULL
};

PGM_P zclLevelControlOMvToLevelCommandArguments[] = {
  "level",
  "transition time",
  NULL
};

PGM_P zclLevelControlOStepCommandArguments[] = {
  "step mode",
  "step size",
  "transition time",
  NULL
};

PGM_P zclLevelControlStepCommandArguments[] = {
  "step mode",
  "step size",
  "transition time",
  NULL
};

EmberCommandEntry zclLevelControlCommands[] = {
  emberCommandEntryActionWithDetails("move", zclLevelControlMoveCommand, "uu", "Command description for Move", zclLevelControlMoveCommandArguments),
  emberCommandEntryActionWithDetails("mv-to-level", zclLevelControlMvToLevelCommand, "uv", "Command description for MoveToLevel", zclLevelControlMvToLevelCommandArguments),
  emberCommandEntryActionWithDetails("o-move", zclLevelControlOMoveCommand, "uu", "Command description for MoveWithOnOff", zclLevelControlOMoveCommandArguments),
  emberCommandEntryActionWithDetails("o-mv-to-level", zclLevelControlOMvToLevelCommand, "uv", "Command description for MoveToLevelWithOnOff", zclLevelControlOMvToLevelCommandArguments),
  emberCommandEntryActionWithDetails("o-step", zclLevelControlOStepCommand, "uuv", "Command description for StepWithOnOff", zclLevelControlOStepCommandArguments),
  emberCommandEntryActionWithDetails("o-stop", zclLevelControlOStopCommand, "", "Command description for StopWithOnOff", NULL),
  emberCommandEntryActionWithDetails("step", zclLevelControlStepCommand, "uuv", "Command description for Step", zclLevelControlStepCommandArguments),
  emberCommandEntryActionWithDetails("stop", zclLevelControlStopCommand, "", "Command description for Stop", NULL),
  emberCommandEntryTerminator()
};

PGM_P zclIdentifyIdCommandArguments[] = {
  "identify time",
  NULL
};

PGM_P zclIdentifyOffCommandArguments[] = {
  "The endpoint on which to stop identifying",
  NULL
};

PGM_P zclIdentifyOnCommandArguments[] = {
  "The endpoint on the device which should begin identifying",
  "The number of seconds to spend identifying",
  NULL
};

PGM_P zclIdentifyTriggerCommandArguments[] = {
  "effect id",
  "effect variant",
  NULL
};

EmberCommandEntry zclIdentifyCommands[] = {
  emberCommandEntryActionWithDetails("id", zclIdentifyIdCommand, "v", "Command description for Identify", zclIdentifyIdCommandArguments),
  emberCommandEntryActionWithDetails("off", zclIdentifyOffCommand, "u", "Creates a message payload for a command that turns identifying off on  ...", zclIdentifyOffCommandArguments),
  emberCommandEntryActionWithDetails("on", zclIdentifyOnCommand, "uv", "Creates the payload for an over the air message that turns identifying ...", zclIdentifyOnCommandArguments),
  emberCommandEntryActionWithDetails("query", zclIdentifyQueryCommand, "", "Command description for IdentifyQuery", NULL),
  emberCommandEntryActionWithDetails("trigger", zclIdentifyTriggerCommand, "uu", "Command description for TriggerEffect", zclIdentifyTriggerCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zclGlobalDirectionCommandArguments[] = {
  "The direction for global commands, 0 = client to server, 1 = server to ...",
  NULL
};

PGM_P zclGlobalDiscComGenCommandArguments[] = {
  "The cluster to find commands on.",
  "The command id to start the command search on.",
  "Max command ids to search for.",
  NULL
};

PGM_P zclGlobalDiscComRecCommandArguments[] = {
  "The cluster to find commands on.",
  "The command id to start the command search on.",
  "Max command ids to search for.",
  NULL
};

PGM_P zclGlobalDiscoverCommandArguments[] = {
  "The cluster id of the cluster to discover.",
  "The attribute id of the attribute to read during discovery.",
  "Max number of discovery responses.",
  NULL
};

PGM_P zclGlobalExpectReportFromMeCommandArguments[] = {
  "The cluster id for the requested report.",
  "The attribute id for the requested report.",
  "Maximum amount of time between reports.",
  NULL
};

PGM_P zclGlobalNwriteCommandArguments[] = {
  "The cluster id of the cluster to read from.",
  "The attribute id of the attribute to read.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};

PGM_P zclGlobalReadCommandArguments[] = {
  "The cluster id of the cluster to read from.",
  "The attribute id of the attribute to read.",
  NULL
};

PGM_P zclGlobalReportCommandArguments[] = {
  "The desired endpoint.",
  "The cluster id.",
  "The attribute id.",
  "The mask.",
  NULL
};

PGM_P zclGlobalReportReadCommandArguments[] = {
  "The cluster id to read from.",
  "The attribute id to read from.",
  "0 for client-to-server, 1 for server-to-client.",
  NULL
};

PGM_P zclGlobalSendMeAReportCommandArguments[] = {
  "The cluster id of the requested report.",
  "The attribute id for requested report.",
  "The two byte ZigBee type value for the requested report.",
  "Minimum number of seconds between reports.",
  "Maximum number of seconds between reports.",
  "Amount of change to trigger a report.",
  NULL
};

PGM_P zclGlobalUwriteCommandArguments[] = {
  "The cluster id of the cluster to write to.",
  "The attribute id of the attribute to write.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};

PGM_P zclGlobalWriteCommandArguments[] = {
  "The cluster id of the cluster to write to.",
  "The attribute id of the attribute to write.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};

EmberCommandEntry zclGlobalCommands[] = {
  emberCommandEntryActionWithDetails("direction", zclGlobalDirectionCommand, "u", "Sets the direction for global commands, either client to server or ser ...", zclGlobalDirectionCommandArguments),
  emberCommandEntryActionWithDetails("disc-com-gen", zclGlobalCommandDiscoveryCommand, "vuu", "Create a Discover Commands Generated command with associated values.", zclGlobalDiscComGenCommandArguments),
  emberCommandEntryActionWithDetails("disc-com-rec", zclGlobalCommandDiscoveryCommand, "vuu", "Create a Discover Commands Received command with associated values.", zclGlobalDiscComRecCommandArguments),
  emberCommandEntryActionWithDetails("discover", zclGlobalDiscoverCommand, "vvu", "Creates discovery message for devices with the associated cluster and  ...", zclGlobalDiscoverCommandArguments),
  emberCommandEntryActionWithDetails("expect-report-from-me", zclGlobalExpectReportFromMeCommand, "vvv", "Create a expect-report-from-me message with associated values.", zclGlobalExpectReportFromMeCommandArguments),
  emberCommandEntryActionWithDetails("nwrite", zclGlobalWriteCommand, "vvub", "Creates a global write command message to write to the cluster and att ...", zclGlobalNwriteCommandArguments),
  emberCommandEntryActionWithDetails("read", zclGlobalReadCommand, "vv", "Creates a global read command message to read from the cluster and att ...", zclGlobalReadCommandArguments),
  emberCommandEntryActionWithDetails("report", zclGlobalReportCommand, "uvvu", "", zclGlobalReportCommandArguments),
  emberCommandEntryActionWithDetails("report-read", zclGlobalReportReadCommand, "vvu", "Creates a global read reporting command for the associated cluster, at ...", zclGlobalReportReadCommandArguments),
  emberCommandEntryActionWithDetails("send-me-a-report", zclGlobalSendMeAReportCommand, "vvuvvb", "Creates a global send me a report command for the associated values.", zclGlobalSendMeAReportCommandArguments),
  emberCommandEntryActionWithDetails("uwrite", zclGlobalWriteCommand, "vvub", "Creates a global write undivided command message to write to the clust ...", zclGlobalUwriteCommandArguments),
  emberCommandEntryActionWithDetails("write", zclGlobalWriteCommand, "vvwb", "Creates a global write command message to write to the cluster and att ...", zclGlobalWriteCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zclColorcontrolEmovehueCommandArguments[] = {
  "move mode",
  "rate",
  NULL
};

PGM_P zclColorcontrolEmovetohueCommandArguments[] = {
  "enhanced hue",
  "direction",
  "transition time",
  NULL
};

PGM_P zclColorcontrolEmovetohueandsatCommandArguments[] = {
  "enhanced hue",
  "saturation",
  "transition time",
  NULL
};

PGM_P zclColorcontrolEstephueCommandArguments[] = {
  "step mode",
  "step size",
  "transition time",
  NULL
};

PGM_P zclColorcontrolLoopCommandArguments[] = {
  "update flags",
  "action",
  "direction",
  "time",
  "start hue",
  NULL
};

PGM_P zclColorcontrolMovecolorCommandArguments[] = {
  "rate x",
  "rate y",
  NULL
};

PGM_P zclColorcontrolMovecolortempCommandArguments[] = {
  "move mode",
  "rate",
  "color temperature minimum",
  "color temperature maximum",
  NULL
};

PGM_P zclColorcontrolMovehueCommandArguments[] = {
  "move mode",
  "rate",
  NULL
};

PGM_P zclColorcontrolMovesatCommandArguments[] = {
  "move mode",
  "rate",
  NULL
};

PGM_P zclColorcontrolMovetocolorCommandArguments[] = {
  "color x",
  "color y",
  "transition time",
  NULL
};

PGM_P zclColorcontrolMovetocolortempCommandArguments[] = {
  "color temperature",
  "transition time",
  NULL
};

PGM_P zclColorcontrolMovetohueCommandArguments[] = {
  "hue",
  "direction",
  "transition time",
  NULL
};

PGM_P zclColorcontrolMovetohueandsatCommandArguments[] = {
  "hue",
  "saturation",
  "transition time",
  NULL
};

PGM_P zclColorcontrolMovetosatCommandArguments[] = {
  "saturation",
  "transition time",
  NULL
};

PGM_P zclColorcontrolStepcolorCommandArguments[] = {
  "step x",
  "step y",
  "transition time",
  NULL
};

PGM_P zclColorcontrolStepcolortempCommandArguments[] = {
  "step mode",
  "step size",
  "transition time",
  "color temperature minimum",
  "color temperature maximum",
  NULL
};

PGM_P zclColorcontrolStephueCommandArguments[] = {
  "step mode",
  "step size",
  "transition time",
  NULL
};

PGM_P zclColorcontrolStepsatCommandArguments[] = {
  "step mode",
  "step size",
  "transition time",
  NULL
};

EmberCommandEntry zclColorcontrolCommands[] = {
  emberCommandEntryActionWithDetails("emovehue", zclColorcontrolEmovehueCommand, "uv", "Command description for EnhancedMoveHue", zclColorcontrolEmovehueCommandArguments),
  emberCommandEntryActionWithDetails("emovetohue", zclColorcontrolEmovetohueCommand, "vuv", "Command description for EnhancedMoveToHue", zclColorcontrolEmovetohueCommandArguments),
  emberCommandEntryActionWithDetails("emovetohueandsat", zclColorcontrolEmovetohueandsatCommand, "vuv", "Command description for EnhancedMoveToHueAndSaturation", zclColorcontrolEmovetohueandsatCommandArguments),
  emberCommandEntryActionWithDetails("estephue", zclColorcontrolEstephueCommand, "uvv", "Command description for EnhancedStepHue", zclColorcontrolEstephueCommandArguments),
  emberCommandEntryActionWithDetails("loop", zclColorcontrolLoopCommand, "uuuvv", "Command description for ColorLoopSet", zclColorcontrolLoopCommandArguments),
  emberCommandEntryActionWithDetails("movecolor", zclColorcontrolMovecolorCommand, "00", "Moves the color.", zclColorcontrolMovecolorCommandArguments),
  emberCommandEntryActionWithDetails("movecolortemp", zclColorcontrolMovecolortempCommand, "uvvv", "Command description for MoveColorTemperature", zclColorcontrolMovecolortempCommandArguments),
  emberCommandEntryActionWithDetails("movehue", zclColorcontrolMovehueCommand, "uu", "Move hue up or down at specified rate.", zclColorcontrolMovehueCommandArguments),
  emberCommandEntryActionWithDetails("movesat", zclColorcontrolMovesatCommand, "uu", "Move saturation up or down at specified rate.", zclColorcontrolMovesatCommandArguments),
  emberCommandEntryActionWithDetails("movetocolor", zclColorcontrolMovetocolorCommand, "vvv", "Move to specified color.", zclColorcontrolMovetocolorCommandArguments),
  emberCommandEntryActionWithDetails("movetocolortemp", zclColorcontrolMovetocolortempCommand, "vv", "Moves the lighting to a specific color temperature.", zclColorcontrolMovetocolortempCommandArguments),
  emberCommandEntryActionWithDetails("movetohue", zclColorcontrolMovetohueCommand, "uuv", "Move to specified hue.", zclColorcontrolMovetohueCommandArguments),
  emberCommandEntryActionWithDetails("movetohueandsat", zclColorcontrolMovetohueandsatCommand, "uuv", "Move to hue and saturation.", zclColorcontrolMovetohueandsatCommandArguments),
  emberCommandEntryActionWithDetails("movetosat", zclColorcontrolMovetosatCommand, "uv", "Move to specified saturation.", zclColorcontrolMovetosatCommandArguments),
  emberCommandEntryActionWithDetails("stepcolor", zclColorcontrolStepcolorCommand, "00v", "Steps the lighting to a specific color.", zclColorcontrolStepcolorCommandArguments),
  emberCommandEntryActionWithDetails("stepcolortemp", zclColorcontrolStepcolortempCommand, "uvvvv", "Command description for StepColorTemperatue", zclColorcontrolStepcolortempCommandArguments),
  emberCommandEntryActionWithDetails("stephue", zclColorcontrolStephueCommand, "uuu", "Step hue up or down by specified size at specified rate.", zclColorcontrolStephueCommandArguments),
  emberCommandEntryActionWithDetails("stepsat", zclColorcontrolStepsatCommand, "uuu", "Step saturation up or down by specified size at specified rate.", zclColorcontrolStepsatCommandArguments),
  emberCommandEntryActionWithDetails("stopmovestep", zclColorcontrolStopmovestepCommand, "", "Command description for StopMoveStep", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry zclBasicCommands[] = {
  emberCommandEntryActionWithDetails("rtfd", zclBasicRtfdCommand, "", "Command that resets all attribute values to factory default.", NULL),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableZclMfgCodeCommandArguments[] = {
  "Manufacturer Specific Id",
  NULL
};

PGM_P emberCommandTableZclTimeCommandArguments[] = {
  "ZigBee UTC time, number of seconds since the year 2000",
  NULL
};

EmberCommandEntry emberCommandTableZclCommands[] = {
  emberCommandEntrySubMenu("basic", zclBasicCommands, ""),
  emberCommandEntrySubMenu("colorcontrol", zclColorcontrolCommands, ""),
  emberCommandEntrySubMenu("global", zclGlobalCommands, ""),
  emberCommandEntrySubMenu("identify", zclIdentifyCommands, ""),
  emberCommandEntrySubMenu("level-control", zclLevelControlCommands, ""),
  emberCommandEntryActionWithDetails("mfg-code", zclMfgCodeCommand, "v", "Sets the two byte manufacturer specific identifier to use for the next ...", emberCommandTableZclMfgCodeCommandArguments),
  emberCommandEntrySubMenu("on-off", zclOnOffCommands, ""),
  emberCommandEntrySubMenu("sm", zclSmCommands, ""),
  emberCommandEntrySubMenu("test", zclTestCommands, ""),
  emberCommandEntryActionWithDetails("time", zclTimeCommand, "w", "Cli command to call emberAfSetTime function documented in af.h", emberCommandTableZclTimeCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P securityMfgTokenSetCommandArguments[] = {
  "magic number",
  "value",
  NULL
};

EmberCommandEntry securityMfgTokenCommands[] = {
  emberCommandEntryActionWithDetails("get", getSetMfgToken, "", "", NULL),
  emberCommandEntryActionWithDetails("set", getSetMfgToken, "wv", "", securityMfgTokenSetCommandArguments),
  emberCommandEntryTerminator()
};

EmberCommandEntry emberCommandTableSecurityCommands[] = {
  emberCommandEntrySubMenu("mfg-token", securityMfgTokenCommands, ""),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableRgbCalibrationCommandArguments[] = {
  "cali_cmd",
  "cali_data",
  NULL
};

EmberCommandEntry emberCommandTableRgbCommands[] = {
  emberCommandEntryActionWithDetails("calibration", rgbCalibrationCommand, "uw", "Command description for sengled_test", emberCommandTableRgbCalibrationCommandArguments),
  emberCommandEntryTerminator()
};

EmberCommandEntry emberCommandTablePrintCommands[] = {
  emberCommandEntryActionWithDetails("attr", emberAfPrintAttributeTable, "", "Print the attribute table.", NULL),
  emberCommandEntryActionWithDetails("time", printTimeCommand, "", "Print out the time information", NULL),
  emberCommandEntryTerminator()
};

PGM_P pluginIdleSleepAwakeWhenNotJoinedCommandArguments[] = {
  "The value indicating whether the device should stay awake when not joi ...",
  NULL
};

PGM_P pluginIdleSleepForceAwakeCommandArguments[] = {
  "The value indicating whether the device should stay awake.",
  NULL
};

EmberCommandEntry pluginIdleSleepCommands[] = {
  emberCommandEntryActionWithDetails("awake-when-not-joined", emberAfPluginIdleSleepAwakeWhenNotJoinedCommand, "u", "Sets whether the device stays awake when not joined to a ZigBee networ ...", pluginIdleSleepAwakeWhenNotJoinedCommandArguments),
  emberCommandEntryActionWithDetails("force-awake", emberAfPluginIdleSleepStayAwakeCommand, "u", "Sets whether the device is forced to stay awake.", pluginIdleSleepForceAwakeCommandArguments),
  emberCommandEntryActionWithDetails("status", emberAfPluginIdleSleepStatusCommand, "", "Display the status of the sleeping behavior.", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry pluginIdentifyCommands[] = {
  emberCommandEntryActionWithDetails("print", emAfPluginIdentifyCliPrint, "", "Print which endpoints are reporting.", NULL),
  emberCommandEntryTerminator()
};

PGM_P pluginCountersSetThresholdCommandArguments[] = {
  "type of counter",
  "Threshold Value",
  NULL
};

EmberCommandEntry pluginCountersCommands[] = {
  emberCommandEntryActionWithDetails("clear", emberAfPluginCountersClear, "", "Clear all counter values.", NULL),
  emberCommandEntryActionWithDetails("print", emberAfPluginCountersPrintCommand, "", "Print all counter values and clear them.", NULL),
  emberCommandEntryActionWithDetails("print-thresholds", emberAfPluginCountersPrintThresholdsCommand, "", "Prints the thresholds of all the counters.", NULL),
  emberCommandEntryActionWithDetails("reset-threshold", emberAfPluginCountersResetThresholds, "", "Resets all thresholds values to 0xFFFF.", NULL),
  emberCommandEntryActionWithDetails("send-request", emberAfPluginCountersSendRequestCommand, "", "Sends a request for ota counters", NULL),
  emberCommandEntryActionWithDetails("set-threshold", emberAfPluginCountersSetThresholdCommand, "uv", "Set a threshold value for a particular type of counter.", pluginCountersSetThresholdCommandArguments),
  emberCommandEntryActionWithDetails("simple-print", emberAfPluginCountersSimplePrintCommand, "", "Print all counter values.", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry pluginConcentratorCommands[] = {
  emberCommandEntryActionWithDetails("agg", emberAfPluginConcentratorAggregationCommand, "", "(Requires Concentrator Support to be enabled on this devic ...", NULL),
  emberCommandEntryActionWithDetails("print-table", emberAfPluginConcentratorPrintSourceRouteTable, "", "Print the source route table.", NULL),
  emberCommandEntryActionWithDetails("start", emberAfPluginConcentratorStartDiscovery, "", "Starts the periodic broadcast of MTORRs", NULL),
  emberCommandEntryActionWithDetails("status", emberAfPluginConcentratorStatus, "", "Prints current status and configured parameters of the concentrator", NULL),
  emberCommandEntryActionWithDetails("stop", emberAfPluginConcentratorStopDiscovery, "", "Stops the periodic broadcast of MTORRs", NULL),
  emberCommandEntryTerminator()
};

PGM_P pluginAddressTableAddCommandArguments[] = {
  "Entry to be added.",
  NULL
};

PGM_P pluginAddressTableLookupCommandArguments[] = {
  "Entry to be looked up.",
  NULL
};

PGM_P pluginAddressTableRemoveCommandArguments[] = {
  "Entry to be removed.",
  NULL
};

EmberCommandEntry pluginAddressTableCommands[] = {
  emberCommandEntryActionWithDetails("add", emberAfPluginAddressTableAddCommand, "b", "Add an entry to the address table.", pluginAddressTableAddCommandArguments),
  emberCommandEntryActionWithDetails("lookup", emberAfPluginAddressTableLookupCommand, "b", "Lookup an entry in the address table.", pluginAddressTableLookupCommandArguments),
  emberCommandEntryActionWithDetails("remove", emberAfPluginAddressTableRemoveCommand, "b", "Remove an entry from the address table.", pluginAddressTableRemoveCommandArguments),
  emberCommandEntryTerminator()
};

EmberCommandEntry emberCommandTablePluginCommands[] = {
  emberCommandEntrySubMenu("address-table", pluginAddressTableCommands, ""),
  emberCommandEntrySubMenu("concentrator", pluginConcentratorCommands, ""),
  emberCommandEntrySubMenu("counters", pluginCountersCommands, ""),
  emberCommandEntrySubMenu("identify", pluginIdentifyCommands, ""),
  emberCommandEntrySubMenu("idle-sleep", pluginIdleSleepCommands, ""),
  emberCommandEntryTerminator()
};

EmberCommandEntry securityApsCommands[] = {
  emberCommandEntryActionWithDetails("off", optionApsSecurityCommand, "", "Turns aps security off", NULL),
  emberCommandEntryActionWithDetails("on", optionApsSecurityCommand, "", "Turns aps security on", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry optionSecurityCommands[] = {
  emberCommandEntrySubMenu("aps", securityApsCommands, ""),
  emberCommandEntryTerminator()
};

EmberCommandEntry optionPrintRxMsgsCommands[] = {
  emberCommandEntryActionWithDetails("disable", optionPrintRxCommand, "", "Disable the printing of received messages.", NULL),
  emberCommandEntryActionWithDetails("enable", optionPrintRxCommand, "", "Enable the printing of received messages.", NULL),
  emberCommandEntryTerminator()
};

PGM_P optionBindingTableSetCommandArguments[] = {
  "one byte index into the binding table",
  "cluster id to send with the discovery message",
  "local endpoint to bind",
  "remote endpoint to bind",
  "8 byte IEEE address provided big endian",
  NULL
};

EmberCommandEntry optionBindingTableCommands[] = {
  emberCommandEntryActionWithDetails("clear", optionBindingTableClearCommand, "", "Clear the binding table", NULL),
  emberCommandEntryActionWithDetails("print", optionBindingTablePrintCommand, "", "Prints out the binding table to the command line.", NULL),
  emberCommandEntryActionWithDetails("set", optionBindingTableSetCommand, "uvuub", "Set a binding table entry for the arguments specified.", optionBindingTableSetCommandArguments),
  emberCommandEntryTerminator()
};

EmberCommandEntry optionApsretryCommands[] = {
  emberCommandEntryActionWithDetails("default", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryActionWithDetails("off", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryActionWithDetails("on", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryTerminator()
};

PGM_P optionAddressTableSetCommandArguments[] = {
  "one byte index into the address table",
  "IEEE address to enter into the address table",
  "two byte node id to enter into the address table",
  NULL
};

EmberCommandEntry optionAddressTableCommands[] = {
  emberCommandEntryActionWithDetails("print", optionAddressTablePrintCommand, "", "Prints the address table.", NULL),
  emberCommandEntryActionWithDetails("set", optionAddressTableSetCommand, "ubv", "Set an entry in the address table according to the arguments specified", optionAddressTableSetCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableOptionDiscCommandArguments[] = {
  "the profile id to send with the discovery message",
  "cluster id to send with the discovery message",
  NULL
};

PGM_P emberCommandTableOptionEdbCommandArguments[] = {
  "The local endpoint whose simple descriptor will be used to create the  ...",
  NULL
};

PGM_P emberCommandTableOptionInstallCodeCommandArguments[] = {
  "index into the link key table",
  "IEEE address to enter into the link key table",
  "install code including two-byte, little-endian CRC",
  NULL
};

PGM_P emberCommandTableOptionLinkCommandArguments[] = {
  "index into the link key table",
  "IEEE address to enter into the link key table",
  "link key to enter into the table",
  NULL
};

EmberCommandEntry emberCommandTableOptionCommands[] = {
  emberCommandEntrySubMenu("address-table", optionAddressTableCommands, ""),
  emberCommandEntrySubMenu("apsretry", optionApsretryCommands, ""),
  emberCommandEntrySubMenu("binding-table", optionBindingTableCommands, ""),
  emberCommandEntryActionWithDetails("disc", optionDiscoverCommand, "vv", "Sends a ZDO Match Descriptor Request for the server side of the specif ...", emberCommandTableOptionDiscCommandArguments),
  emberCommandEntryActionWithDetails("edb", optionEndDeviceBindCommand, "u", "Sends a ZDO End Device Bind Request using the given local endpoint.", emberCommandTableOptionEdbCommandArguments),
  emberCommandEntryActionWithDetails("install-code", optionInstallCodeCommand, "ubb", "Derives a link key from an install code and sets it in the link key ta ...", emberCommandTableOptionInstallCodeCommandArguments),
  emberCommandEntryActionWithDetails("link", optionLinkCommand, "ubb", "Sets a link key in the link key tabl ...", emberCommandTableOptionLinkCommandArguments),
  emberCommandEntrySubMenu("print-rx-msgs", optionPrintRxMsgsCommands, ""),
  emberCommandEntryActionWithDetails("register", optionRegisterCommand, "", "Initiates Smart Energy Registration including Key Establishmen ...", NULL),
  emberCommandEntrySubMenu("security", optionSecurityCommands, ""),
  emberCommandEntryTerminator()
};

EmberCommandEntry networkFindCommands[] = {
  emberCommandEntryActionWithDetails("joinable", findJoinableNetworkCommand, "", "Begins a search for a joinable networ ...", NULL),
  emberCommandEntryActionWithDetails("unused", findUnusedPanIdCommand, "", "Begins a search for an unused Channel and Pan I ...", NULL),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableNetworkBroadPjoinCommandArguments[] = {
  "Number of seconds during which devices will be allowed to join the net ...",
  NULL
};

PGM_P emberCommandTableNetworkChangeChannelCommandArguments[] = {
  "The channel to change to.",
  NULL
};

PGM_P emberCommandTableNetworkExtpanidCommandArguments[] = {
  "The bytes for the extended pan id",
  NULL
};

PGM_P emberCommandTableNetworkFormCommandArguments[] = {
  "The channel on which to form the network",
  "One byte signed value indicating the TX power that the radio should be ...",
  "Two byte pan id for the network",
  NULL
};

PGM_P emberCommandTableNetworkJoinCommandArguments[] = {
  "The channel on which to form the network",
  "One byte signed value indicating the TX power that the radio should be ...",
  "Two byte pan id for the network",
  NULL
};

PGM_P emberCommandTableNetworkPjoinCommandArguments[] = {
  "Number of seconds during which devices will be allowed to join the net ...",
  NULL
};

PGM_P emberCommandTableNetworkRejoinCommandArguments[] = {
  "Boolean indicating whether the device can rejoin secure or no ...",
  "4 byte channel mask which should be used to search for the network to  ...",
  NULL
};

PGM_P emberCommandTableNetworkSetCommandArguments[] = {
  "The network index to use for CLI commands",
  NULL
};

EmberCommandEntry emberCommandTableNetworkCommands[] = {
  emberCommandEntryActionWithDetails("broad-pjoin", networkPermitJoinCommand, "u", "Permit joining on the network for a given number of seconds AND broadc ...", emberCommandTableNetworkBroadPjoinCommandArguments),
  emberCommandEntryActionWithDetails("change-channel", networkChangeChannelCommand, "u", "Attempts to change device over to a different channel given in the cha ...", emberCommandTableNetworkChangeChannelCommandArguments),
  emberCommandEntryActionWithDetails("extpanid", networkExtendedPanIdCommand, "b", "Write the extended pan id for the device.", emberCommandTableNetworkExtpanidCommandArguments),
  emberCommandEntrySubMenu("find", networkFindCommands, ""),
  emberCommandEntryActionWithDetails("form", networkFormCommand, "usv", "Create a network on the given channel, power and panId.", emberCommandTableNetworkFormCommandArguments),
  emberCommandEntryActionWithDetails("id", networkIdCommand, "", "Prints the current Node ID, EUI64, and Pan ID.", NULL),
  emberCommandEntryActionWithDetails("init", networkInitCommand, "", "Initialize a network; this is a test command used for tc-swap-out test ...", NULL),
  emberCommandEntryActionWithDetails("join", networkJoinCommand, "usv", "Join an existing network on the given channel, power and panId.", emberCommandTableNetworkJoinCommandArguments),
  emberCommandEntryActionWithDetails("leave", networkLeaveCommand, "", "Leave the current network.", NULL),
  emberCommandEntryActionWithDetails("pjoin", networkPermitJoinCommand, "u", "Permit joining on the network for a given number of seconds", emberCommandTableNetworkPjoinCommandArguments),
  emberCommandEntryActionWithDetails("rejoin", networkRejoinCommand, "uw", "Rejoin an existing network in a secure or insecure manner.", emberCommandTableNetworkRejoinCommandArguments),
  emberCommandEntryActionWithDetails("set", networkSetCommand, "u", "Set the network index used by all future CLI command ...", emberCommandTableNetworkSetCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableKeysDeleteCommandArguments[] = {
  "index into the security key table",
  NULL
};

EmberCommandEntry emberCommandTableKeysCommands[] = {
  emberCommandEntryActionWithDetails("clear", keysClearCommand, "", "Clear all security keys", NULL),
  emberCommandEntryActionWithDetails("delete", keysDeleteCommand, "u", "Delete a security key from a given index", emberCommandTableKeysDeleteCommandArguments),
  emberCommandEntryActionWithDetails("print", keysPrintCommand, "", "Print all security keys out to the command line.", NULL),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableInterpanGroupCommandArguments[] = {
  "group id to send to",
  "destination pan id",
  "destination profile ID",
  NULL
};

PGM_P emberCommandTableInterpanLongCommandArguments[] = {
  "long ieee address to send the interpan message to",
  "two byte destination PA ID",
  "two byte destination profile ID",
  "two byte options",
  NULL
};

PGM_P emberCommandTableInterpanShortCommandArguments[] = {
  "group id to send to",
  "destination pan id",
  "destination profile ID",
  NULL
};

EmberCommandEntry emberCommandTableInterpanCommands[] = {
  emberCommandEntryActionWithDetails("group", interpanCommand, "vvv", "send an interpan message to a group id.", emberCommandTableInterpanGroupCommandArguments),
  emberCommandEntryActionWithDetails("long", interpanLongCommand, "bvvv", "Send an interpan message to a long address (8 byte eui64)", emberCommandTableInterpanLongCommandArguments),
  emberCommandEntryActionWithDetails("short", interpanCommand, "vvv", "Send an interpan message to a short id.", emberCommandTableInterpanShortCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableEndpointDisableCommandArguments[] = {
  "Endpoint in question.",
  NULL
};

PGM_P emberCommandTableEndpointEnableCommandArguments[] = {
  "Endpoint in question.",
  NULL
};

EmberCommandEntry emberCommandTableEndpointCommands[] = {
  emberCommandEntryActionWithDetails("disable", enableDisableEndpoint, "u", "Disable the endpoint for processing ZCL messages.", emberCommandTableEndpointDisableCommandArguments),
  emberCommandEntryActionWithDetails("enable", enableDisableEndpoint, "u", "Enable the endpoint for processing ZCL messages.", emberCommandTableEndpointEnableCommandArguments),
  emberCommandEntryActionWithDetails("print", endpointPrint, "", "Print the status of all the endpoints.", NULL),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableDebugprintOffCommandArguments[] = {
  "The debug area mask listed in the <application>.h file",
  NULL
};

PGM_P emberCommandTableDebugprintOnCommandArguments[] = {
  "The debug area mask listed in the <application>.h file",
  NULL
};

EmberCommandEntry emberCommandTableDebugprintCommands[] = {
  emberCommandEntryActionWithDetails("all_off", emberAfPrintAllOff, "", "Turns off all debug printing", NULL),
  emberCommandEntryActionWithDetails("all_on", emberAfPrintAllOn, "", "Turns on all compiled in debug printing", NULL),
  emberCommandEntryActionWithDetails("off", printOffCommand, "u", "Turns off compiled in debug printing for a specific debug printing are ...", emberCommandTableDebugprintOffCommandArguments),
  emberCommandEntryActionWithDetails("on", printOnCommand, "u", "Turns on compiled in debug printing for a specific debug printing area ...", emberCommandTableDebugprintOnCommandArguments),
  emberCommandEntryActionWithDetails("status", emberAfPrintStatus, "", "Prints out the current settings for debug printing on the device", NULL),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableChangekeyLinkCommandArguments[] = {
  "The link key provided as a 16 byte array",
  NULL
};

PGM_P emberCommandTableChangekeyNetworkCommandArguments[] = {
  "The network key provided as a 16 byte array",
  NULL
};

EmberCommandEntry emberCommandTableChangekeyCommands[] = {
  emberCommandEntryActionWithDetails("link", changeKeyCommand, "b", "Change the link key to the one provided in the 16 byte array argument  ...", emberCommandTableChangekeyLinkCommandArguments),
  emberCommandEntryActionWithDetails("network", changeKeyCommand, "b", "Change the network key to the 16 byte array provided as an argument to ...", emberCommandTableChangekeyNetworkCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableBsendCommandArguments[] = {
  "source endpoint to send a binding based message from",
  NULL
};

PGM_P emberCommandTableEchoCommandArguments[] = {
  "boolean indicating whether to turn echo on (1) or off (0)",
  NULL
};

PGM_P emberCommandTableRawCommandArguments[] = {
  "two byte cluster id",
  "two byte short id of the time server",
  NULL
};

PGM_P emberCommandTableReadCommandArguments[] = {
  "endpoint of the attribute to read",
  "cluster id of the attribute to read",
  "attribute id of the attribute to read",
  "direction mask of the attribute to read (client=0 or server=1)",
  NULL
};

PGM_P emberCommandTableSendCommandArguments[] = {
  "short id of the device to send the message to",
  "The endpoint to send the message from",
  "The endpoint to send the message to",
  NULL
};

PGM_P emberCommandTableSendMulticastCommandArguments[] = {
  "group id of the multicast group to send the message to",
  "The endpoint to send the message from",
  NULL
};

PGM_P emberCommandTableTimesyncCommandArguments[] = {
  "two byte short id of the time server",
  "source endpoint to send time sync from",
  "destination endpoint to expect response on",
  NULL
};

PGM_P emberCommandTableWriteCommandArguments[] = {
  "endpoint of the attribute to write",
  "cluster id of the attribute to write",
  "attribute id of the attribute to write",
  "direction mask of the attribute to write (client=0 or server=1)",
  "the attribute type as listed in the generated file attribute-type.h",
  "string of bytes you wish to write into the attribute table.",
  NULL
};

EmberCommandEntry emberCommandTable[] = {
  emberCommandEntryActionWithDetails("bsend", emAfCliBsendCommand, "u", "send using a binding based on the clusterId in the globalApsFrame and  ...", emberCommandTableBsendCommandArguments),
  emberCommandEntrySubMenu("changekey", emberCommandTableChangekeyCommands, ""),
  emberCommandEntrySubMenu("debugprint", emberCommandTableDebugprintCommands, ""),
  emberCommandEntryActionWithDetails("echo", echoCommand, "u", "Turns echo on the command line on or off depending on the argument", emberCommandTableEchoCommandArguments),
  emberCommandEntrySubMenu("endpoint", emberCommandTableEndpointCommands, ""),
  emberCommandEntryActionWithDetails("help", helpCommand, "", "Prints out the cli command options for the device", NULL),
  emberCommandEntryActionWithDetails("info", emAfCliInfoCommand, "", "Gives information about the local node", NULL),
  emberCommandEntrySubMenu("interpan", emberCommandTableInterpanCommands, ""),
  emberCommandEntrySubMenu("keys", emberCommandTableKeysCommands, ""),
  emberCommandEntryActionWithDetails("libs", printAllLibraryStatus, "", "Lists which optional libraries of the stack are implemented on this de ...", NULL),
  emberCommandEntrySubMenu("network", emberCommandTableNetworkCommands, ""),
  emberCommandEntrySubMenu("option", emberCommandTableOptionCommands, ""),
  emberCommandEntrySubMenu("plugin", emberCommandTablePluginCommands, ""),
  emberCommandEntrySubMenu("print", emberCommandTablePrintCommands, ""),
  emberCommandEntryActionWithDetails("raw", emAfCliRawCommand, "vb", "Creates a message by specifying the raw byte ...", emberCommandTableRawCommandArguments),
  emberCommandEntryActionWithDetails("read", emAfCliReadCommand, "uvvu", "Read an attribute from the local attribute tabl ...", emberCommandTableReadCommandArguments),
  emberCommandEntryActionWithDetails("reset", resetCommand, "", "resets the device", NULL),
  emberCommandEntrySubMenu("rgb", emberCommandTableRgbCommands, ""),
  emberCommandEntrySubMenu("security", emberCommandTableSecurityCommands, ""),
  emberCommandEntryActionWithDetails("send", emAfCliSendCommand, "vuu", "Send a pre-buffered message from a given endpoint to an endpoint on a  ...", emberCommandTableSendCommandArguments),
  emberCommandEntryActionWithDetails("send_multicast", emAfCliSendCommand, "vu", "Send a pre-buffered multicast message to a given group id from a given ...", emberCommandTableSendMulticastCommandArguments),
  emberCommandEntryActionWithDetails("timesync", emAfCliTimesyncCommand, "vuu", "This sends a read attr for the time of the device specifie ...", emberCommandTableTimesyncCommandArguments),
  emberCommandEntryActionWithDetails("version", emAfCliVersionCommand, "", "Shows the version of the software", NULL),
  emberCommandEntryActionWithDetails("write", emAfCliWriteCommand, "uvvuub", "Write an attribute value into the local attribute table", emberCommandTableWriteCommandArguments),
  emberCommandEntrySubMenu("zcl", emberCommandTableZclCommands, ""),
  emberCommandEntrySubMenu("zdo", emberCommandTableZdoCommands, ""),
  CUSTOM_COMMANDS
  emberCommandEntryTerminator()
};



