var group__cli =
[
    [ "Attribute Management", "group__attribute.html", "group__attribute" ],
    [ "Building and Sending Messages", "group__build-send-msg.html", "group__build-send-msg" ],
    [ "Endpoint Manipulation", "group__endpoint.html", "group__endpoint" ],
    [ "General", "group__general.html", "group__general" ],
    [ "Global ZCL", "group__zcl-global.html", "group__zcl-global" ],
    [ "Informational", "group__info.html", "group__info" ],
    [ "Network", "group__network.html", "group__network" ],
    [ "Security", "group__security.html", "group__security" ],
    [ "Test Harness", "group__test.html", "group__test" ],
    [ "ZigBee Device Object Commands (ZDO)", "group__zdo.html", "group__zdo" ],
    [ "Cluster Commands: BACnet Protocol Tunnel", "group__bacnet-protocol-tunnel.html", "group__bacnet-protocol-tunnel" ],
    [ "Cluster Commands: Basic", "group__basic.html", "group__basic" ],
    [ "Cluster Commands: Color Control", "group__color-control.html", "group__color-control" ],
    [ "Cluster Commands: Demand Response and Load Control", "group__demand-response-and-load-control.html", "group__demand-response-and-load-control" ],
    [ "Cluster Commands: Door Lock", "group__door-lock.html", "group__door-lock" ],
    [ "Cluster Commands: Generic Tunnel", "group__generic-tunnel.html", "group__generic-tunnel" ],
    [ "Cluster Commands: Groups", "group__groups.html", "group__groups" ],
    [ "Cluster Commands: IAS ACE", "group__ias-ace.html", "group__ias-ace" ],
    [ "Cluster Commands: IAS Zone", "group__ias-zone.html", "group__ias-zone" ],
    [ "Cluster Commands: Identify", "group__identify.html", "group__identify" ],
    [ "Cluster Commands: Level Control", "group__level-control.html", "group__level-control" ],
    [ "Cluster Commands: Messaging", "group__messaging.html", "group__messaging" ],
    [ "Cluster Commands: On/off", "group__on-off.html", "group__on-off" ],
    [ "Cluster Commands: Price", "group__price.html", "group__price" ],
    [ "Cluster Commands: Scenes", "group__scenes.html", "group__scenes" ],
    [ "Cluster Commands: Simple Metering", "group__simple-metering.html", "group__simple-metering" ],
    [ "Cluster Commands: Thermostat", "group__thermostat.html", "group__thermostat" ],
    [ "Cluster Commands: Tunneling", "group__tunneling.html", "group__tunneling" ],
    [ "Cluster Commands: Window Covering", "group__window-covering.html", "group__window-covering" ],
    [ "Plugin Commands: Address Table", "group__plugin-address-table.html", "group__plugin-address-table" ],
    [ "Plugin Commands: Button Joining", "group__plugin-button-joining.html", "group__plugin-button-joining" ],
    [ "Plugin Commands: Concentrator", "group__plugin-concentrator.html", "group__plugin-concentrator" ],
    [ "Plugin Commands: Counters", "group__plugin-counters.html", "group__plugin-counters" ],
    [ "Plugin Commands: Demand Response and Load Control", "group__plugin-drlc.html", "group__plugin-drlc" ],
    [ "Plugin Commands: Demand Response and Load Control Server", "group__plugin-drlc-server.html", "group__plugin-drlc-server" ],
    [ "Plugin Commands: Fragmentation", "group__plugin-fragmentation.html", "group__plugin-fragmentation" ],
    [ "Plugin Commands: Groups Server", "group__plugin-groups-server.html", "group__plugin-groups-server" ],
    [ "Plugin Commands: Identify", "group__plugin-identify.html", "group__plugin-identify" ],
    [ "Plugin Commands: Idle/Sleep", "group__plugin-idle-sleep.html", "group__plugin-idle-sleep" ],
    [ "Plugin Commands: Key Establishment", "group__plugin-key-establishment.html", "group__plugin-key-establishment" ],
    [ "Plugin Commands: Messaging Client", "group__plugin-messaging-client.html", "group__plugin-messaging-client" ],
    [ "Plugin Commands: Messaging Server", "group__plugin-messaging-server.html", "group__plugin-messaging-server" ],
    [ "Plugin Commands: Partner Link Key Exchange", "group__plugin-partner-link-key-exchange.html", "group__plugin-partner-link-key-exchange" ],
    [ "Plugin Commands: Price Client", "group__plugin-price-client.html", "group__plugin-price-client" ],
    [ "Plugin Commands: Price Server", "group__plugin-price-server.html", "group__plugin-price-server" ],
    [ "Plugin Commands: Reporting", "group__plugin-reporting.html", "group__plugin-reporting" ],
    [ "Plugin Commands: Scenes Server", "group__plugin-scenes.html", "group__plugin-scenes" ],
    [ "Plugin Commands: Simple Metering Server", "group__plugin-simple-metering-server.html", "group__plugin-simple-metering-server" ],
    [ "Plugin Commands: Smart Energy Registration", "group__plugin-smart-energy-registration.html", "group__plugin-smart-energy-registration" ],
    [ "Plugin Commands: Tunneling Client", "group__plugin-tunneling-client.html", "group__plugin-tunneling-client" ],
    [ "Plugin Commands: Tunneling Server", "group__plugin-tunneling-server.html", "group__plugin-tunneling-server" ]
];